version: 2
updates:
  - package-ecosystem: cargo
    directory: "/rustybot-server/"
    schedule: 
      interval: "daily"
  - package-ecosystem: cargo
    directory: "/rustybot-macros/"
    schedule: 
      interval: "daily"